#! /bin/sh -e

case "$1" in
	configure)
		adduser --system --home /opt/satoshilabs/bitcore-testnet/home \
			--quiet --gecos "satoshilabs bitcore-testnet" bitcore-testnet
		chown -R bitcore-testnet /opt/satoshilabs/bitcore-testnet/home
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
	;;
	
	*)
	    echo "postinst called with unknown argument \`$1'" >&2
	    exit 1
	;;
esac


#DEBHELPER#

exit 0
