#! /bin/sh -e

case "$1" in
	install|upgrade)
		echo '# installed by bitcore-testnet package' > /etc/apt/sources.list.d/bitcore-testnet-nodesource.list
		echo 'deb https://deb.nodesource.com/node_4.x jessie main' >> /etc/apt/sources.list.d/bitcore-testnet-nodesource.list
		curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
		;;
	abort-upgrade)
	;;
	*)
	    echo "preinst called with unknown argument \`$1'" >&2
	    exit 1
	;;
esac

exit 0

