#!/bin/bash -e

INSTALL_PATH="/opt/satoshilabs/bitcore-2x/"
BIN=$(realpath "$INSTALL_PATH"/bitcore/node_modules/bitcore-node/bin/bitcoin-*/bin/)
DATA="$INSTALL_PATH/home/.bitcore/data"
CONF="$DATA/bitcoin.conf"

exec sudo -u bitcore-2x "$BIN/bitcoind" --conf="$CONF" --datadir="$DATA" "$@"

