#! /bin/sh -e

case "$1" in
	configure)
		adduser --system --home /opt/satoshilabs/bitcore-ltc/home \
			--quiet --gecos "satoshilabs bitcore-ltc" bitcore-ltc
		chown -R bitcore-ltc /opt/satoshilabs/bitcore-ltc/home
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
	;;
	
	*)
	    echo "postinst called with unknown argument \`$1'" >&2
	    exit 1
	;;
esac


#DEBHELPER#

exit 0
