#! /bin/sh -e

case "$1" in
	configure)
		adduser --system --home /opt/satoshilabs/bitcore-bcc/home \
			--quiet --gecos "satoshilabs bitcore-bcc" bitcore-bcc
		chown -R bitcore-bcc /opt/satoshilabs/bitcore-bcc/home
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
	;;
	
	*)
	    echo "postinst called with unknown argument \`$1'" >&2
	    exit 1
	;;
esac


#DEBHELPER#

exit 0
