#! /bin/sh -e

case "$1" in
	configure)
		adduser --system --home /opt/satoshilabs/bitcore-btc/home \
			--quiet --gecos "satoshilabs bitcore-btc" bitcore-btc
		chown -R bitcore-btc /opt/satoshilabs/bitcore-btc/home
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
	;;
	
	*)
	    echo "postinst called with unknown argument \`$1'" >&2
	    exit 1
	;;
esac


#DEBHELPER#

exit 0
