#! /bin/sh -e

case "$1" in
	configure)
		adduser --system --home /opt/satoshilabs/bitcore-tbcc/home \
			--quiet --gecos "satoshilabs bitcore-tbcc" bitcore-tbcc
		chown -R bitcore-tbcc /opt/satoshilabs/bitcore-tbcc/home
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
	;;
	
	*)
	    echo "postinst called with unknown argument \`$1'" >&2
	    exit 1
	;;
esac


#DEBHELPER#

exit 0
