#! /bin/sh -e

case "$1" in
	configure)
		adduser --system --home /opt/satoshilabs/bitcore-dash/home \
			--quiet --gecos "satoshilabs bitcore-dash" bitcore-dash
		chown -R bitcore-dash /opt/satoshilabs/bitcore-dash/home
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
	;;
	
	*)
	    echo "postinst called with unknown argument \`$1'" >&2
	    exit 1
	;;
esac


#DEBHELPER#

exit 0
